# MQTT settings
mqtt:
  # MQTT base topic for ambilight MQTT messages
  # <base_topic>/color - same message as on <light_topic>
  # <base_topic>/power
  base_topic: zigbee2mqtt
  # MQTT topic for ambilight MQTT messages
  light_topic: zigbee2mqttlight/set
  # MQTT server URL
  server: 'iot.eclipse.org'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password